<a href="https://colab.research.google.com/github/promihamid/GithubPrac/blob/main/Day2_OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
dataset = pd.read_csv("/content/loan.csv")

In [6]:
dataset.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [9]:
dataset.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           15
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

**Filling missing value**

In [8]:
dataset["Gender"].fillna(dataset["Gender"].mode()[0], inplace=True)
dataset["Married"].fillna(dataset["Married"].mode()[0], inplace=True)
dataset["Self_Employed"].fillna(dataset["Self_Employed"].mode()[0],inplace=True)

/tmp/ipython-input-8-2428251816.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["Gender"].fillna(dataset["Gender"].mode()[0], inplace=True)
/tmp/ipython-input-8-2428251816.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["Married"].fillna(dataset["Married"].mode()[0], inplace=True)
/tmp/ipython-input-8-2428251816.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["Self_Employed"].fillna(dataset["Self_Employed"].mode()[0],inplace=True)

**One hot encoding**

In [11]:
en_data = dataset[["Gender","Married","Self_Employed"]]

**One hot encoding using get_dummies() method**

In [22]:
pd.get_dummies(en_data) #drop_first for avoiding redundancy, get_dummies() used for one-hot encoding

,Gender_Female,Gender_Male,Married_No,Married_Yes,Self_Employed_No,Self_Employed_Yes
0,False,True,True,False,True,False
1,False,True,False,True,True,False
2,False,True,False,True,False,True
3,False,True,False,True,True,False
4,False,True,True,False,True,False
...,...,...,...,...,...,...
609,True,False,True,False,True,False
610,False,True,False,True,True,False
611,False,True,False,True,True,False
612,False,True,False,True,True,False
613,True,False,True,False,False,True

**ekhane value still string e ache but we want it in numerical format. So use OneHotEncoder from sklearn <br><br>
One hot encoding using sklearn**

In [23]:
from sklearn.preprocessing import OneHotEncoder

In [26]:
ohe = OneHotEncoder(drop="first")
ar = ohe.fit_transform(en_data).toarray() # fit_transform--> 1st e data ke dekhe then sckitlearn er algo apply kore, then transform kore numerical e

use toarray() to convert the data into array. but we want out DATA AS DATAFRAME FORMAT NOT IN ARRAY FORMAT. so use dataframe() method

In [30]:
pd.DataFrame(ar,columns=["Gender_Male","Married_Yes","Self_Employed_Yes"])

     Gender_Male  Married_Yes  Self_Employed_Yes
0            1.0          0.0                0.0
1            1.0          1.0                0.0
2            1.0          1.0                1.0
3            1.0          1.0                0.0
4            1.0          0.0                0.0
..           ...          ...                ...
609          0.0          0.0                0.0
610          1.0          1.0                0.0
611          1.0          1.0                0.0
612          1.0          1.0                0.0
613          0.0          0.0                1.0

[614 rows x 3 columns]